import jwt

token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdGF0dXMiOiJzdWNjZXNzIiwiZGF0YSI6eyJpZCI6MSwidXNlcm5hbWUiOiIiLCJlbWFpbCI6ImFkbWluQGp1aWNlLXNoLm9wIiwicGFzc3dvcmQiOiIwMTkyMDIzYTdiYmQ3MzI1MDUxNmYwNjlkZjE4YjUwMCIsInJvbGUiOiJhZG1pbiIsImRlbHV4ZVRva2VuIjoiIiwibGFzdExvZ2luSXAiOiIiLCJwcm9maWxlSW1hZ2UiOiJhc3NldHMvcHVibGljL2ltYWdlcy91cGxvYWRzL2RlZmF1bHRBZG1pbi5wbmciLCJ0b3RwU2VjcmV0IjoiIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjQtMTItMjUgMjA6MjU6MjIuNDc4ICswMDowMCIsInVwZGF0ZWRBdCI6IjIwMjQtMTItMjUgMjA6MjU6MjIuNDc4ICswMDowMCIsImRlbGV0ZWRBdCI6bnVsbH0sImlhdCI6MTczNTE1ODQzOX0.KqsdgF8ZdkPZVGlOFtaAh0_-FTl5GM73DA4btTSYtGwhqTfY-YmGShoeuG1oxYkDTwvKKnBcwAd20P_nyi7_cxcc0zNWJJGtXdLVrrByADdLbspFTAws8ZQTdIw8IaUOo2UHkm_JoecJoyka-aXyijJ7ox20PZtLoCKYoNDvTV0"

decoded_token = jwt.decode(token, options={"verify_signature": False})
print(decoded_token)
